apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-nativeha-server
  namespace: ibm-mq
spec:
  secretName: mq-nativeha-server-tls
  commonName: mq-nativeha
  dnsNames:
    - mq-nativeha
    - "*.apps.itz-h9zmp8.hub04-lb.techzone.ibm.com"
  issuerRef:
    name: servers-ca-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  usages:
    - digital signature
    - key encipherment
    - server auth
