apiVersion: v1
data:
  app-definitions.mqsc: |
    DEFINE CHANNEL('TEST.SVRCONN') CHLTYPE(SVRCONN) REPLACE TRPTYPE(TCP) SSLCAUTH(REQUIRED) SSLCIPH(ANY_TLS12_OR_HIGHER) DESCR('Dedicated SVRCONN for mq-test producer/consumer')
    SET CHLAUTH('TEST.SVRCONN') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('Deny by default on this channel') ACTION(REPLACE)
    SET CHLAUTH('TEST.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('OU=producer') USERSRC(MAP) MCAUSER('app-producer') DESCR('Map any client cert with OU=producer to app-producer') ACTION(REPLACE)
    SET CHLAUTH('TEST.SVRCONN') TYPE(SSLPEERMAP) SSLPEER('OU=consumer') USERSRC(MAP) MCAUSER('app-consumer') DESCR('Map any client cert with OU=consumer to app-consumer') ACTION(REPLACE)
    SET AUTHREC PRINCIPAL('app-producer') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE('TEST.*') PRINCIPAL('app-producer') OBJTYPE(QUEUE) AUTHADD(PUT)
    SET AUTHREC PRINCIPAL('app-consumer') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE('TEST.*') PRINCIPAL('app-consumer') OBJTYPE(QUEUE) AUTHADD(GET,BROWSE,INQ)
kind: ConfigMap
metadata:
  name: mq-nativeha-mqsc
  namespace: ibm-mq