apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-test-config
  namespace: mq-test
data:
  MQ_HOST: mq-nativeha-ibm-mq-qm-ibm-mq.apps.itz-h9zmp8.hub04-lb.techzone.ibm.com
  MQ_PORT: "443"
  MQ_QMGR: MQNATIVEHA
  MQ_CHANNEL: TEST.SVRCONN
  MQ_QUEUE: TEST.QUEUE
  MQ_KEYSTORE_PATH: /etc/mq-test/keystore/keystore.p12
  MQ_TRUSTSTORE_PATH: /etc/mq-test/truststore/truststore.p12
